//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Active()
        {
            this.ActiveAlbum = new HashSet<ActiveAlbum>();
            this.ActiveComplain = new HashSet<ActiveComplain>();
            this.Activehide = new HashSet<Activehide>();
        }
    
        public int actno { get; set; }
        public string actname { get; set; }
        public string actinfo { get; set; }
        public string orienroll { get; set; }
        public string recenroll { get; set; }
        public string image_url { get; set; }
        public Nullable<int> Joinsum { get; set; }
        public Nullable<int> Viewsum { get; set; }
        public Nullable<System.DateTime> DDLine { get; set; }
        public int Holder { get; set; }
        public int Location { get; set; }
        public Nullable<int> ac_state { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveAlbum> ActiveAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveComplain> ActiveComplain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activehide> Activehide { get; set; }
    }
}
