//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMusics
    {
        public int cm_id { get; set; }
        public string cm_name { get; set; }
        public string music_url { get; set; }
        public Nullable<int> music_down { get; set; }
        public System.DateTime music_upTime { get; set; }
        public string music_type { get; set; }
    }
}
