//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoodsComment()
        {
            this.Addcomment = new HashSet<Addcomment>();
        }
    
        public int goodscommentid { get; set; }
        public int userId { get; set; }
        public int goodsid { get; set; }
        public System.DateTime commmenttime { get; set; }
        public string content { get; set; }
        public int addcom { get; set; }
        public Nullable<int> Sorce { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Addcomment> Addcomment { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Users Users { get; set; }
    }
}
