//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mails
    {
        public int id { get; set; }
        public Nullable<int> sent_user { get; set; }
        public Nullable<int> recip_user { get; set; }
        public string title { get; set; }
        public string mail { get; set; }
        public Nullable<int> mail_state { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
