//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailChatRecords
    {
        public int id { get; set; }
        public Nullable<int> recordid { get; set; }
        public Nullable<int> sentid { get; set; }
        public Nullable<int> recipid { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> sent_time { get; set; }
        public Nullable<int> record_state { get; set; }
        public Nullable<int> otherstate { get; set; }
    
        public virtual MailChat MailChat { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
