//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail_View
    {
        public string img { get; set; }
        public string goodsname { get; set; }
        public decimal price { get; set; }
        public int qty { get; set; }
        public int userId { get; set; }
        public int orderdetailsid { get; set; }
    }
}
