//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMusics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMusics()
        {
            this.ActiveAlbum = new HashSet<ActiveAlbum>();
            this.MusicCollectRecord = new HashSet<MusicCollectRecord>();
            this.MusicComment = new HashSet<MusicComment>();
            this.PlayRecord = new HashSet<PlayRecord>();
        }
    
        public int music_id { get; set; }
        public string music_name { get; set; }
        public int user_id { get; set; }
        public string imgage_url { get; set; }
        public string music_url { get; set; }
        public Nullable<int> musicType_id { get; set; }
        public Nullable<int> upType_id { get; set; }
        public Nullable<int> music_like { get; set; }
        public string music_info { get; set; }
        public Nullable<System.DateTime> upTime { get; set; }
        public Nullable<int> listen_times { get; set; }
        public int music_state { get; set; }
        public int music_check { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActiveAlbum> ActiveAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicCollectRecord> MusicCollectRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicComment> MusicComment { get; set; }
        public virtual MusicType MusicType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayRecord> PlayRecord { get; set; }
        public virtual UpType UpType { get; set; }
        public virtual Users Users { get; set; }
    }
}
