//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Videos()
        {
            this.VideoCollectRecord = new HashSet<VideoCollectRecord>();
            this.VideoComment = new HashSet<VideoComment>();
        }
    
        public int video_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string video_name { get; set; }
        public string video_photo { get; set; }
        public string video_url { get; set; }
        public Nullable<int> videoType_id { get; set; }
        public Nullable<int> video_look { get; set; }
        public string video_info { get; set; }
        public Nullable<System.DateTime> video_upTime { get; set; }
        public string relate_music { get; set; }
        public int video_state { get; set; }
        public int video_check { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoCollectRecord> VideoCollectRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> VideoComment { get; set; }
        public virtual VideoType VideoType { get; set; }
    }
}
