//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_showactive
    {
        public int actno { get; set; }
        public string actname { get; set; }
        public string actinfo { get; set; }
        public string orienroll { get; set; }
        public string recenroll { get; set; }
        public string image_url { get; set; }
        public Nullable<int> Joinsum { get; set; }
        public Nullable<int> Viewsum { get; set; }
        public Nullable<System.DateTime> DDLine { get; set; }
        public int Holder { get; set; }
        public int Location { get; set; }
    }
}
